[phases.setup]
nixPkgs = ["python311", "poetry"]

[phases.install]
cmds = [
    "cd backend",
    "poetry config virtualenvs.create false", 
    "poetry install --only=main --no-root"
]

[start]
cmd = "./start.sh"