[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[environments.production]
variables = { ENVIRONMENT = "production", DEBUG = "false" }