[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[environments.production]
variables = { ENVIRONMENT = "production", DEBUG = "false" }