"""
FIA v3.0 - Training Slide Entity
SQLAlchemy model for training_slides table
"""

from sqlalchemy import Column, String, Text, Integer, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import uuid

from app.infrastructure.database import Base


class TrainingSlide(Base):
    __tablename__ = "training_slides"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    submodule_id = Column(UUID(as_uuid=True), ForeignKey("training_submodules.id", ondelete="CASCADE"), nullable=False)
    order_in_submodule = Column(Integer, nullable=False)  # Order within submodule
    title = Column(String, nullable=False)  # Pre-generated by Gemini
    content = Column(Text, nullable=True)  # Generated on-demand when learner reaches slide
    generated_at = Column(DateTime(timezone=True), nullable=True)  # When content was generated
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    submodule = relationship("TrainingSubmodule", back_populates="slides")